name: Format check

on:
  push:
    branches:
      - main
      - 'release-*'
    tags: '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3
        with:
          version: '1.10'
          arch: x64
      - uses: julia-actions/cache@a7bed9df697e5d7309d68afe7542a87621a8b6c8 # v3.3.0
      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="2.12.4"))'
      - name: Check formatting
        run: |
          julia -e 'using JuliaFormatter; format(".", verbose=true)'
          git diff --exit-code
